version: '3'
services:
  postgres:
    image: 'postgres:9.6.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'advancenotedb'
